# Generated by Django 5.2.8 on 2025-11-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PAYEAgent',
            fields=[
                ('payer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_rc_num', models.CharField(max_length=50, unique=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
