# Generated by Django 5.2.8 on 2025-11-24 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payeregistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payeagent',
            name='date_of_registration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payeagent',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='payeagent',
            name='agent_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
