# Generated by Django 5.2.8 on 2025-11-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payeregistration', '0002_payeagent_date_of_registration_payeagent_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payeagent',
            old_name='password',
            new_name='agent_password',
        ),
        migrations.RenameField(
            model_name='payeagent',
            old_name='date_of_registration',
            new_name='registration_date',
        ),
    ]
