# Generated by Django 5.2.8 on 2025-11-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payeregistration', '0003_rename_password_payeagent_agent_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payeagent',
            name='agent_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
