# Generated by Django 5.2.8 on 2025-11-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payeregistration', '0004_alter_payeagent_agent_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payeagent',
            name='agent_password',
            field=models.CharField(max_length=128),
        ),
    ]
