# Generated by Django 5.2.8 on 2025-12-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayeComputation',
            fields=[
                ('computation_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=20)),
                ('employee_name', models.CharField(max_length=100)),
                ('gross_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paye_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('computation_date', models.DateField(auto_now_add=True)),
                ('tax_year', models.CharField(max_length=9)),
            ],
        ),
    ]
