# Generated by Django 5.2.8 on 2025-12-13 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payecomputation', '0002_staff'),
        ('payeregistration', '0005_alter_payeagent_agent_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payecomputation',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payeregistration.payeagent'),
        ),
    ]
