# Generated by Django 5.2.8 on 2025-12-13 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payecomputation', '0003_alter_payecomputation_employee_id'),
        ('payeregistration', '0005_alter_payeagent_agent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='payecomputation',
            name='employer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payeregistration.payeagent'),
        ),
        migrations.AlterField(
            model_name='payecomputation',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payecomputation.staff'),
        ),
    ]
