# Generated by Django 5.2.8 on 2025-12-13 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payecomputation', '0004_payecomputation_employer_id_and_more'),
        ('payeregistration', '0005_alter_payeagent_agent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payeregistration.payeagent'),
        ),
    ]
